version: '3'
services:
  ros2yolo-service:
    # build:
    #   context: ..
    #   dockerfile: .devcontainer/Dockerfile
    image: yc-dlan/rc2026:yolo-ros #cpu镜像
    container_name: yolo_container_cpu
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./../..:/home/Elaina/yolo
      - /dev:/dev
    network_mode: host
    pid: "host" # 添加 pid 命名空间共享
    ipc: "host" # 添加 ipc 命名空间共享    
    privileged: true
    stdin_open: true
    tty: true
    user: "Elaina" 
    # runtime: "nvidia"
    working_dir: "/home/Elaina/yolo" # 指定默认工作目录
